// @generated by protoc-gen-connect-query v1.1.2 with parameter "target=ts,import_extension=.ts"
// @generated from file v1/admin/AdminData.proto (package server.admin, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Empty, MethodKind } from "@bufbuild/protobuf";
import { AdminDataRequest, AdminDataResponse, AdminListRequest, AdminListResponse, AdminUpdateDataRequest } from "./AdminData_pb.ts";

/**
 * @generated from rpc server.admin.AdminDataController.GetByID
 */
export const getByID = {
  localName: "getByID",
  name: "GetByID",
  kind: MethodKind.Unary,
  I: AdminDataRequest,
  O: AdminDataResponse,
  service: {
    typeName: "server.admin.AdminDataController"
  }
} as const;

/**
 * @generated from rpc server.admin.AdminDataController.Update
 */
export const update = {
  localName: "update",
  name: "Update",
  kind: MethodKind.Unary,
  I: AdminUpdateDataRequest,
  O: AdminDataResponse,
  service: {
    typeName: "server.admin.AdminDataController"
  }
} as const;

/**
 * @generated from rpc server.admin.AdminDataController.GetAll
 */
export const getAll = {
  localName: "getAll",
  name: "GetAll",
  kind: MethodKind.Unary,
  I: AdminListRequest,
  O: AdminListResponse,
  service: {
    typeName: "server.admin.AdminDataController"
  }
} as const;

/**
 * @generated from rpc server.admin.AdminDataController.Delete
 */
export const delete$ = {
  localName: "delete",
  name: "Delete",
  kind: MethodKind.Unary,
  I: AdminDataRequest,
  O: Empty,
  service: {
    typeName: "server.admin.AdminDataController"
  }
} as const;
