// @generated by protoc-gen-connect-es v1.1.3 with parameter "target=ts,import_extension=.ts"
// @generated from file v1/admin/AdminData.proto (package server.admin, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AdminDataRequest, AdminDataResponse, AdminListRequest, AdminListResponse, AdminUpdateDataRequest } from "./AdminData_pb.ts";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service server.admin.AdminDataController
 */
export const AdminDataController = {
  typeName: "server.admin.AdminDataController",
  methods: {
    /**
     * @generated from rpc server.admin.AdminDataController.GetByID
     */
    getByID: {
      name: "GetByID",
      I: AdminDataRequest,
      O: AdminDataResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.admin.AdminDataController.Update
     */
    update: {
      name: "Update",
      I: AdminUpdateDataRequest,
      O: AdminDataResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.admin.AdminDataController.GetAll
     */
    getAll: {
      name: "GetAll",
      I: AdminListRequest,
      O: AdminListResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.admin.AdminDataController.Delete
     */
    delete: {
      name: "Delete",
      I: AdminDataRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
} as const;

