// @generated by protoc-gen-connect-es v1.1.3 with parameter "target=ts,import_extension=.ts"
// @generated from file v1/admin/AdminData.proto (package server.admin, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AdminDataResponse, AdminUpdateDataRequest } from "./AdminData_pb.ts";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service server.admin.AdminDataController
 */
export const AdminDataController = {
  typeName: "server.admin.AdminDataController",
  methods: {
    /**
     * @generated from rpc server.admin.AdminDataController.Update
     */
    update: {
      name: "Update",
      I: AdminUpdateDataRequest,
      O: AdminDataResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

