// @generated by protoc-gen-connect-es v1.1.3 with parameter "target=ts,import_extension=.ts"
// @generated from file v1/admin/AnonAuth.proto (package server.admin, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AdminAuthRequest, AnonAuthTokenResponse, ResetPasswordRequest, SetNewPasswordRequest } from "./AnonAuth_pb.ts";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service server.admin.AnonAuthController
 */
export const AnonAuthController = {
  typeName: "server.admin.AnonAuthController",
  methods: {
    /**
     * トークン不要
     *
     * @generated from rpc server.admin.AnonAuthController.SignUp
     */
    signUp: {
      name: "SignUp",
      I: AdminAuthRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.admin.AnonAuthController.SignIn
     */
    signIn: {
      name: "SignIn",
      I: AdminAuthRequest,
      O: AnonAuthTokenResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.admin.AnonAuthController.ResetPasswordMail
     */
    resetPasswordMail: {
      name: "ResetPasswordMail",
      I: ResetPasswordRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.admin.AnonAuthController.SetNewPassword
     */
    setNewPassword: {
      name: "SetNewPassword",
      I: SetNewPasswordRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
} as const;

