// @generated by protoc-gen-connect-query v1.1.2 with parameter "target=ts,import_extension=.ts"
// @generated from file v1/admin/AnonAuth.proto (package server.admin, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Empty, MethodKind } from "@bufbuild/protobuf";
import { AdminAuthRequest, AnonAuthTokenResponse, ResetPasswordRequest, SetNewPasswordRequest } from "./AnonAuth_pb.ts";

/**
 * トークン不要
 *
 * @generated from rpc server.admin.AnonAuthController.SignUp
 */
export const signUp = {
  localName: "signUp",
  name: "SignUp",
  kind: MethodKind.Unary,
  I: AdminAuthRequest,
  O: Empty,
  service: {
    typeName: "server.admin.AnonAuthController"
  }
} as const;

/**
 * @generated from rpc server.admin.AnonAuthController.SignIn
 */
export const signIn = {
  localName: "signIn",
  name: "SignIn",
  kind: MethodKind.Unary,
  I: AdminAuthRequest,
  O: AnonAuthTokenResponse,
  service: {
    typeName: "server.admin.AnonAuthController"
  }
} as const;

/**
 * @generated from rpc server.admin.AnonAuthController.ResetPasswordMail
 */
export const resetPasswordMail = {
  localName: "resetPasswordMail",
  name: "ResetPasswordMail",
  kind: MethodKind.Unary,
  I: ResetPasswordRequest,
  O: Empty,
  service: {
    typeName: "server.admin.AnonAuthController"
  }
} as const;

/**
 * @generated from rpc server.admin.AnonAuthController.SetNewPassword
 */
export const setNewPassword = {
  localName: "setNewPassword",
  name: "SetNewPassword",
  kind: MethodKind.Unary,
  I: SetNewPasswordRequest,
  O: Empty,
  service: {
    typeName: "server.admin.AnonAuthController"
  }
} as const;
