// @generated by protoc-gen-connect-es v1.1.3 with parameter "target=ts,import_extension=.ts"
// @generated from file v1/admin/Auth.proto (package server.admin, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AdminAuthRequest, AdminAuthResponse, AdminRefreshTokenRequest, AdminRegisterRequest, ResetPasswordRequest, UpdateEmailRequest, UpdatePasswordRequest } from "./Auth_pb.ts";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service server.admin.AuthController
 */
export const AuthController = {
  typeName: "server.admin.AuthController",
  methods: {
    /**
     * @generated from rpc server.admin.AuthController.Register
     */
    register: {
      name: "Register",
      I: AdminRegisterRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.admin.AuthController.SignUp
     */
    signUp: {
      name: "SignUp",
      I: AdminAuthRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.admin.AuthController.SignOut
     */
    signOut: {
      name: "SignOut",
      I: Empty,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.admin.AuthController.Refresh
     */
    refresh: {
      name: "Refresh",
      I: AdminRefreshTokenRequest,
      O: AdminAuthResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.admin.AuthController.SignIn
     */
    signIn: {
      name: "SignIn",
      I: AdminAuthRequest,
      O: AdminAuthResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.admin.AuthController.ResetPasswordMail
     */
    resetPasswordMail: {
      name: "ResetPasswordMail",
      I: ResetPasswordRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.admin.AuthController.UpdatePassword
     */
    updatePassword: {
      name: "UpdatePassword",
      I: UpdatePasswordRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.admin.AuthController.UpdateEmail
     */
    updateEmail: {
      name: "UpdateEmail",
      I: UpdateEmailRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
} as const;

