// @generated by protoc-gen-connect-es v1.1.3 with parameter "target=ts"
// @generated from file v1/admin/Coupon.proto (package server.admin, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AffectedCountResponse, CouponIDRequest, CreateCustomCouponRequest, UserAttachedCouponsResponse, UserIDRequest } from "./Coupon_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service server.admin.AdminCouponController
 */
export const AdminCouponController = {
  typeName: "server.admin.AdminCouponController",
  methods: {
    /**
     * @generated from rpc server.admin.AdminCouponController.GetUserCouponList
     */
    getUserCouponList: {
      name: "GetUserCouponList",
      I: UserIDRequest,
      O: UserAttachedCouponsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.admin.AdminCouponController.CreateCustomCoupon
     */
    createCustomCoupon: {
      name: "CreateCustomCoupon",
      I: CreateCustomCouponRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.admin.AdminCouponController.SaveCustomCoupon
     */
    saveCustomCoupon: {
      name: "SaveCustomCoupon",
      I: CouponIDRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.admin.AdminCouponController.AttachCustomCouponToAllUser
     */
    attachCustomCouponToAllUser: {
      name: "AttachCustomCouponToAllUser",
      I: CouponIDRequest,
      O: AffectedCountResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

