// @generated by protoc-gen-connect-query v1.1.2 with parameter "target=ts,import_extension=.ts"
// @generated from file v1/admin/Coupon.proto (package server.admin, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Empty, MethodKind } from "@bufbuild/protobuf";
import { AffectedCountResponse, CouponIDRequest, CouponListResponse, CreateCustomCouponRequest, DefaultNoticesResponse, SaveCustomCouponRequest, UserAttachedCouponsResponse, UserCouponRequest } from "./Coupon_pb.ts";
import { Coupon } from "../shared/Coupon_pb.ts";
import { Pager } from "../shared/Pager_pb.ts";

/**
 * @generated from rpc server.admin.AdminCouponController.GetUserCouponList
 */
export const getUserCouponList = {
  localName: "getUserCouponList",
  name: "GetUserCouponList",
  kind: MethodKind.Unary,
  I: UserCouponRequest,
  O: UserAttachedCouponsResponse,
  service: {
    typeName: "server.admin.AdminCouponController"
  }
} as const;

/**
 * @generated from rpc server.admin.AdminCouponController.CreateCustomCoupon
 */
export const createCustomCoupon = {
  localName: "createCustomCoupon",
  name: "CreateCustomCoupon",
  kind: MethodKind.Unary,
  I: CreateCustomCouponRequest,
  O: Coupon,
  service: {
    typeName: "server.admin.AdminCouponController"
  }
} as const;

/**
 * @generated from rpc server.admin.AdminCouponController.SaveCustomCoupon
 */
export const saveCustomCoupon = {
  localName: "saveCustomCoupon",
  name: "SaveCustomCoupon",
  kind: MethodKind.Unary,
  I: SaveCustomCouponRequest,
  O: Empty,
  service: {
    typeName: "server.admin.AdminCouponController"
  }
} as const;

/**
 * @generated from rpc server.admin.AdminCouponController.GetDefaultNotices
 */
export const getDefaultNotices = {
  localName: "getDefaultNotices",
  name: "GetDefaultNotices",
  kind: MethodKind.Unary,
  I: Empty,
  O: DefaultNoticesResponse,
  service: {
    typeName: "server.admin.AdminCouponController"
  }
} as const;

/**
 * @generated from rpc server.admin.AdminCouponController.GetCustomCouponByID
 */
export const getCustomCouponByID = {
  localName: "getCustomCouponByID",
  name: "GetCustomCouponByID",
  kind: MethodKind.Unary,
  I: CouponIDRequest,
  O: Coupon,
  service: {
    typeName: "server.admin.AdminCouponController"
  }
} as const;

/**
 * @generated from rpc server.admin.AdminCouponController.GetCustomCouponList
 */
export const getCustomCouponList = {
  localName: "getCustomCouponList",
  name: "GetCustomCouponList",
  kind: MethodKind.Unary,
  I: Pager,
  O: CouponListResponse,
  service: {
    typeName: "server.admin.AdminCouponController"
  }
} as const;

/**
 * @generated from rpc server.admin.AdminCouponController.AttachCustomCouponToAllUser
 */
export const attachCustomCouponToAllUser = {
  localName: "attachCustomCouponToAllUser",
  name: "AttachCustomCouponToAllUser",
  kind: MethodKind.Unary,
  I: CouponIDRequest,
  O: AffectedCountResponse,
  service: {
    typeName: "server.admin.AdminCouponController"
  }
} as const;
