// @generated by protoc-gen-connect-query v1.4.2 with parameter "target=ts,import_extension=.ts"
// @generated from file v1/admin/Store.proto (package server.admin, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Empty, MethodKind } from "@bufbuild/protobuf";
import { QRResponse, Store, StoreIDRequest, StoreRegisterRequest, Stores, StoreUpdateRequest, UnlimitQRResponse } from "./Store_pb.ts";

/**
 * @generated from rpc server.admin.StoreController.GetByID
 */
export const getByID = {
  localName: "getByID",
  name: "GetByID",
  kind: MethodKind.Unary,
  I: StoreIDRequest,
  O: Store,
  service: {
    typeName: "server.admin.StoreController"
  }
} as const;

/**
 * @generated from rpc server.admin.StoreController.GetAll
 */
export const getAll = {
  localName: "getAll",
  name: "GetAll",
  kind: MethodKind.Unary,
  I: Empty,
  O: Stores,
  service: {
    typeName: "server.admin.StoreController"
  }
} as const;

/**
 * @generated from rpc server.admin.StoreController.GetActiveAll
 */
export const getActiveAll = {
  localName: "getActiveAll",
  name: "GetActiveAll",
  kind: MethodKind.Unary,
  I: Empty,
  O: Stores,
  service: {
    typeName: "server.admin.StoreController"
  }
} as const;

/**
 * @generated from rpc server.admin.StoreController.Register
 */
export const register = {
  localName: "register",
  name: "Register",
  kind: MethodKind.Unary,
  I: StoreRegisterRequest,
  O: Store,
  service: {
    typeName: "server.admin.StoreController"
  }
} as const;

/**
 * @generated from rpc server.admin.StoreController.Update
 */
export const update = {
  localName: "update",
  name: "Update",
  kind: MethodKind.Unary,
  I: StoreUpdateRequest,
  O: Store,
  service: {
    typeName: "server.admin.StoreController"
  }
} as const;

/**
 * @generated from rpc server.admin.StoreController.RegenQRCode
 */
export const regenQRCode = {
  localName: "regenQRCode",
  name: "RegenQRCode",
  kind: MethodKind.Unary,
  I: StoreIDRequest,
  O: QRResponse,
  service: {
    typeName: "server.admin.StoreController"
  }
} as const;

/**
 * @generated from rpc server.admin.StoreController.RegenUnlimitQRCode
 */
export const regenUnlimitQRCode = {
  localName: "regenUnlimitQRCode",
  name: "RegenUnlimitQRCode",
  kind: MethodKind.Unary,
  I: StoreIDRequest,
  O: UnlimitQRResponse,
  service: {
    typeName: "server.admin.StoreController"
  }
} as const;
