// @generated by protoc-gen-connect-es v1.1.3 with parameter "target=ts,import_extension=.ts"
// @generated from file v1/admin/Store.proto (package server.admin, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QRResponse, SoreIDRequest, StoreRegisterRequest, StoreUpdateRequest, UnlimitQRResponse } from "./Store_pb.ts";
import { Store, Stores } from "../shared/Store_pb.ts";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service server.admin.StoreController
 */
export const StoreController = {
  typeName: "server.admin.StoreController",
  methods: {
    /**
     * @generated from rpc server.admin.StoreController.GetByID
     */
    getByID: {
      name: "GetByID",
      I: SoreIDRequest,
      O: Store,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.admin.StoreController.GetAll
     */
    getAll: {
      name: "GetAll",
      I: Empty,
      O: Stores,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.admin.StoreController.Register
     */
    register: {
      name: "Register",
      I: StoreRegisterRequest,
      O: Store,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.admin.StoreController.Update
     */
    update: {
      name: "Update",
      I: StoreUpdateRequest,
      O: Store,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.admin.StoreController.RegenQRCode
     */
    regenQRCode: {
      name: "RegenQRCode",
      I: SoreIDRequest,
      O: QRResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.admin.StoreController.RegenUnlimitQRCode
     */
    regenUnlimitQRCode: {
      name: "RegenUnlimitQRCode",
      I: SoreIDRequest,
      O: UnlimitQRResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

