// @generated by protoc-gen-connect-es v1.1.3 with parameter "target=ts"
// @generated from file v1/admin/UserCheckin.proto (package server.admin, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CheckinsResponse, GetRecentAllCheckinRequest, UserCheckinRequest } from "./UserCheckin_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service server.admin.UserCheckinController
 */
export const UserCheckinController = {
  typeName: "server.admin.UserCheckinController",
  methods: {
    /**
     * @generated from rpc server.admin.UserCheckinController.GetAllRecent
     */
    getAllRecent: {
      name: "GetAllRecent",
      I: GetRecentAllCheckinRequest,
      O: CheckinsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.admin.UserCheckinController.GetUserLog
     */
    getUserLog: {
      name: "GetUserLog",
      I: UserCheckinRequest,
      O: CheckinsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

