// @generated by protoc-gen-connect-query v1.1.2 with parameter "target=ts,import_extension=.ts"
// @generated from file v1/admin/UserData.proto (package server.admin, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Empty, MethodKind } from "@bufbuild/protobuf";
import { UserDataResponse, UserDeleteRequest, UserGetIDRequest, UserListFilterRequest, UserListResponse, UserUpdateDataRequest } from "./UserData_pb.ts";

/**
 * @generated from rpc server.admin.UserDataController.GetByID
 */
export const getByID = {
  localName: "getByID",
  name: "GetByID",
  kind: MethodKind.Unary,
  I: UserGetIDRequest,
  O: UserDataResponse,
  service: {
    typeName: "server.admin.UserDataController"
  }
} as const;

/**
 * @generated from rpc server.admin.UserDataController.Update
 */
export const update = {
  localName: "update",
  name: "Update",
  kind: MethodKind.Unary,
  I: UserUpdateDataRequest,
  O: UserDataResponse,
  service: {
    typeName: "server.admin.UserDataController"
  }
} as const;

/**
 * @generated from rpc server.admin.UserDataController.Delete
 */
export const delete$ = {
  localName: "delete",
  name: "Delete",
  kind: MethodKind.Unary,
  I: UserDeleteRequest,
  O: Empty,
  service: {
    typeName: "server.admin.UserDataController"
  }
} as const;

/**
 * @generated from rpc server.admin.UserDataController.GetList
 */
export const getList = {
  localName: "getList",
  name: "GetList",
  kind: MethodKind.Unary,
  I: UserListFilterRequest,
  O: UserListResponse,
  service: {
    typeName: "server.admin.UserDataController"
  }
} as const;
