// @generated by protoc-gen-connect-query v1.1.2 with parameter "target=ts,import_extension=.ts"
// @generated from file v1/admin/UserCheckin.proto (package server.admin, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MethodKind } from "@bufbuild/protobuf";
import { CheckinsResponse, GetRecentAllCheckinRequest, UserCheckinRequest } from "./UserCheckin_pb.ts";

/**
 * @generated from rpc server.admin.UserCheckinController.GetAllRecent
 */
export const getAllRecent = {
  localName: "getAllRecent",
  name: "GetAllRecent",
  kind: MethodKind.Unary,
  I: GetRecentAllCheckinRequest,
  O: CheckinsResponse,
  service: {
    typeName: "server.admin.UserCheckinController"
  }
} as const;

/**
 * @generated from rpc server.admin.UserCheckinController.GetUserLog
 */
export const getUserLog = {
  localName: "getUserLog",
  name: "GetUserLog",
  kind: MethodKind.Unary,
  I: UserCheckinRequest,
  O: CheckinsResponse,
  service: {
    typeName: "server.admin.UserCheckinController"
  }
} as const;
