import type { Metadata } from "next"
import { Inter } from "next/font/google"
// import './globals.css'
import "@/styles/globals.css"

import { Titlebar } from "@/components/parts/titlebar"

// const inter = Inter({ subsets: ['latin'] })
export const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout(props: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Titlebar />
        {props.children}
      </body>
    </html>
  )
}
