// @generated by protoc-gen-connect-es v1.1.3 with parameter "target=ts"
// @generated from file v1/user/Auth.proto (package server.user, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { UserRegisterRequest } from "./UserData_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";
import { ResetPasswordRequest, UpdateEmailRequest, UpdatePasswordRequest, UserAuthRequest, UserAuthResponse } from "./Auth_pb.js";

/**
 * @generated from service server.user.AuthController
 */
export const AuthController = {
  typeName: "server.user.AuthController",
  methods: {
    /**
     * @generated from rpc server.user.AuthController.Register
     */
    register: {
      name: "Register",
      I: UserRegisterRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.user.AuthController.SignUp
     */
    signUp: {
      name: "SignUp",
      I: UserAuthRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.user.AuthController.SignIn
     */
    signIn: {
      name: "SignIn",
      I: UserAuthRequest,
      O: UserAuthResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.user.AuthController.ResetPasswordMail
     */
    resetPasswordMail: {
      name: "ResetPasswordMail",
      I: ResetPasswordRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.user.AuthController.UpdatePassword
     */
    updatePassword: {
      name: "UpdatePassword",
      I: UpdatePasswordRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.user.AuthController.UpdateEmail
     */
    updateEmail: {
      name: "UpdateEmail",
      I: UpdateEmailRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
} as const;

