// @generated by protoc-gen-connect-query v1.4.2 with parameter "target=ts,import_extension=.ts"
// @generated from file v1/user/Banner.proto (package server.user, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Empty, MethodKind } from "@bufbuild/protobuf";
import { BannerResponse } from "./Banner_pb.ts";

/**
 * TOPバナーの取得 URLと画像URLを配列で返す
 *
 * @generated from rpc server.user.BannerController.GetBanner
 */
export const getBanner = {
  localName: "getBanner",
  name: "GetBanner",
  kind: MethodKind.Unary,
  I: Empty,
  O: BannerResponse,
  service: {
    typeName: "server.user.BannerController"
  }
} as const;
