// @generated by protoc-gen-connect-es v1.1.3 with parameter "target=ts"
// @generated from file v1/user/Book.proto (package server.user, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Empty, MethodKind } from "@bufbuild/protobuf";
import { BookIDRequest, BookResponse, BooksResponse, ReserveRequest } from "./Book_pb.js";

/**
 * @generated from service server.user.BookController
 */
export const BookController = {
  typeName: "server.user.BookController",
  methods: {
    /**
     * @generated from rpc server.user.BookController.GetMyBook
     */
    getMyBook: {
      name: "GetMyBook",
      I: Empty,
      O: BooksResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.user.BookController.GetBookByID
     */
    getBookByID: {
      name: "GetBookByID",
      I: BookIDRequest,
      O: BookResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.user.BookController.Cancel
     */
    cancel: {
      name: "Cancel",
      I: BookIDRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.user.BookController.Reserve
     */
    reserve: {
      name: "Reserve",
      I: ReserveRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
} as const;

