// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=.ts"
// @generated from file v1/user/Book.proto (package server.user, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Empty, MethodKind } from "@bufbuild/protobuf";
import { BookIDRequest, BookMentenanceInfoResponse, BookResponse, BooksResponse, PlanDetailRequest, PlanSearchRequest, PlanStayDetailResponse, ReserveRequest, SearchPlanResponse } from "./Book_pb.ts";

/**
 * @generated from service server.user.BookController
 */
export const BookController = {
  typeName: "server.user.BookController",
  methods: {
    /**
     * 現在の自身の予約状況
     *
     * @generated from rpc server.user.BookController.GetMyBook
     */
    getMyBook: {
      name: "GetMyBook",
      I: Empty,
      O: BooksResponse,
      kind: MethodKind.Unary,
    },
    /**
     * 現在の自身の特定の予約の詳細を取得
     *
     * @generated from rpc server.user.BookController.GetBookByID
     */
    getBookByID: {
      name: "GetBookByID",
      I: BookIDRequest,
      O: BookResponse,
      kind: MethodKind.Unary,
    },
    /**
     * 予約のキャンセル
     *
     * @generated from rpc server.user.BookController.Cancel
     */
    cancel: {
      name: "Cancel",
      I: BookIDRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * 予約情報からプランの予約
     *
     * @generated from rpc server.user.BookController.Reserve
     */
    reserve: {
      name: "Reserve",
      I: ReserveRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * 現在メンテナンス中かどうか
     *
     * @generated from rpc server.user.BookController.GetMentenanceInfo
     */
    getMentenanceInfo: {
      name: "GetMentenanceInfo",
      I: Empty,
      O: BookMentenanceInfoResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

/**
 * @generated from service server.user.PlanController
 */
export const PlanController = {
  typeName: "server.user.PlanController",
  methods: {
    /**
     * @generated from rpc server.user.PlanController.Search
     */
    search: {
      name: "Search",
      I: PlanSearchRequest,
      O: SearchPlanResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.user.PlanController.GetDetail
     */
    getDetail: {
      name: "GetDetail",
      I: PlanDetailRequest,
      O: PlanStayDetailResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

