// @generated by protoc-gen-connect-query v1.4.2 with parameter "target=ts,import_extension=.ts"
// @generated from file v1/user/Checkin.proto (package server.user, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Empty, MethodKind } from "@bufbuild/protobuf";
import { CheckinRequest, CheckinResponse, StampCardResponse } from "./Checkin_pb.ts";

/**
 * 自身のスタンプカード取得（現在のチェックイン済情報と店舗のスタンプ画像が届く）
 *
 * @generated from rpc server.user.CheckinController.GetStampCard
 */
export const getStampCard = {
  localName: "getStampCard",
  name: "GetStampCard",
  kind: MethodKind.Unary,
  I: Empty,
  O: StampCardResponse,
  service: {
    typeName: "server.user.CheckinController"
  }
} as const;

/**
 * 店舗に対するチェックイン（QRコード利用）
 *
 * @generated from rpc server.user.CheckinController.Checkin
 */
export const checkin = {
  localName: "checkin",
  name: "Checkin",
  kind: MethodKind.Unary,
  I: CheckinRequest,
  O: CheckinResponse,
  service: {
    typeName: "server.user.CheckinController"
  }
} as const;
