// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=.ts"
// @generated from file v1/user/Checkin.proto (package server.user, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Empty, MethodKind } from "@bufbuild/protobuf";
import { CheckinRequest, CheckinResponse, StampCardResponse } from "./Checkin_pb.ts";

/**
 * @generated from service server.user.CheckinController
 */
export const CheckinController = {
  typeName: "server.user.CheckinController",
  methods: {
    /**
     * 自身のスタンプカード取得（現在のチェックイン済情報と店舗のスタンプ画像が届く）
     *
     * @generated from rpc server.user.CheckinController.GetStampCard
     */
    getStampCard: {
      name: "GetStampCard",
      I: Empty,
      O: StampCardResponse,
      kind: MethodKind.Unary,
    },
    /**
     * 店舗に対するチェックイン（QRコード利用）
     *
     * @generated from rpc server.user.CheckinController.Checkin
     */
    checkin: {
      name: "Checkin",
      I: CheckinRequest,
      O: CheckinResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

