// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=.ts"
// @generated from file v1/user/Messages.proto (package server.user, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MessageRequest, MessagesResponse } from "./Messages_pb.ts";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service server.user.MessageController
 */
export const MessageController = {
  typeName: "server.user.MessageController",
  methods: {
    /**
     * 　ポップアップメッセージのリストを取得する（最後に取得したIDを元にリクエスト）
     *
     * @generated from rpc server.user.MessageController.GetMessagesAfter
     */
    getMessagesAfter: {
      name: "GetMessagesAfter",
      I: MessageRequest,
      O: MessagesResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

