// @generated by protoc-gen-connect-es v1.1.3 with parameter "target=ts"
// @generated from file v1/user/Messages.proto (package server.user, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MessageRequest, MessagesResponse } from "./Messages_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service server.user.MessageController
 */
export const MessageController = {
  typeName: "server.user.MessageController",
  methods: {
    /**
     * @generated from rpc server.user.MessageController.GetMessagesAfter
     */
    getMessagesAfter: {
      name: "GetMessagesAfter",
      I: MessageRequest,
      O: MessagesResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

