// @generated by protoc-gen-connect-query v1.4.2 with parameter "target=ts,import_extension=.ts"
// @generated from file v1/user/MyCoupon.proto (package server.user, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Empty, MethodKind } from "@bufbuild/protobuf";
import { CouponIDRequest, MyCouponsResponse } from "./MyCoupon_pb.ts";
import { Coupon } from "../shared/Coupon_pb.ts";

/**
 * 現在ユーザーが持っているクーポン一覧を取得する
 *
 * @generated from rpc server.user.MyCouponController.GetList
 */
export const getList = {
  localName: "getList",
  name: "GetList",
  kind: MethodKind.Unary,
  I: Empty,
  O: MyCouponsResponse,
  service: {
    typeName: "server.user.MyCouponController"
  }
} as const;

/**
 * @generated from rpc server.user.MyCouponController.GetExpiredList
 */
export const getExpiredList = {
  localName: "getExpiredList",
  name: "GetExpiredList",
  kind: MethodKind.Unary,
  I: Empty,
  O: MyCouponsResponse,
  service: {
    typeName: "server.user.MyCouponController"
  }
} as const;

/**
 * @generated from rpc server.user.MyCouponController.GetUsedList
 */
export const getUsedList = {
  localName: "getUsedList",
  name: "GetUsedList",
  kind: MethodKind.Unary,
  I: Empty,
  O: MyCouponsResponse,
  service: {
    typeName: "server.user.MyCouponController"
  }
} as const;

/**
 * クーポンの詳細
 *
 * @generated from rpc server.user.MyCouponController.GetDetail
 */
export const getDetail = {
  localName: "getDetail",
  name: "GetDetail",
  kind: MethodKind.Unary,
  I: CouponIDRequest,
  O: Coupon,
  service: {
    typeName: "server.user.MyCouponController"
  }
} as const;

/**
 * クーポンの使用
 *
 * @generated from rpc server.user.MyCouponController.Use
 */
export const use = {
  localName: "use",
  name: "Use",
  kind: MethodKind.Unary,
  I: CouponIDRequest,
  O: Empty,
  service: {
    typeName: "server.user.MyCouponController"
  }
} as const;
