// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=.ts"
// @generated from file v1/user/MyCoupon.proto (package server.user, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Empty, MethodKind } from "@bufbuild/protobuf";
import { CouponIDRequest, MyCouponsResponse } from "./MyCoupon_pb.ts";
import { Coupon } from "../shared/Coupon_pb.ts";

/**
 * @generated from service server.user.MyCouponController
 */
export const MyCouponController = {
  typeName: "server.user.MyCouponController",
  methods: {
    /**
     * 現在ユーザーが持っているクーポン一覧を取得する
     *
     * @generated from rpc server.user.MyCouponController.GetList
     */
    getList: {
      name: "GetList",
      I: Empty,
      O: MyCouponsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.user.MyCouponController.GetExpiredList
     */
    getExpiredList: {
      name: "GetExpiredList",
      I: Empty,
      O: MyCouponsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.user.MyCouponController.GetUsedList
     */
    getUsedList: {
      name: "GetUsedList",
      I: Empty,
      O: MyCouponsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * クーポンの詳細
     *
     * @generated from rpc server.user.MyCouponController.GetDetail
     */
    getDetail: {
      name: "GetDetail",
      I: CouponIDRequest,
      O: Coupon,
      kind: MethodKind.Unary,
    },
    /**
     * クーポンの使用
     *
     * @generated from rpc server.user.MyCouponController.Use
     */
    use: {
      name: "Use",
      I: CouponIDRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
} as const;

