// @generated by protoc-gen-connect-es v1.1.3 with parameter "target=ts"
// @generated from file v1/user/MyCoupon.proto (package server.user, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CouponIDRequest, MyCouponsResponse } from "./MyCoupon_pb.js";
import { Coupon } from "../shared/Coupon_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service server.user.MyCouponController
 */
export const MyCouponController = {
  typeName: "server.user.MyCouponController",
  methods: {
    /**
     * @generated from rpc server.user.MyCouponController.GetDetail
     */
    getDetail: {
      name: "GetDetail",
      I: CouponIDRequest,
      O: Coupon,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.user.MyCouponController.GetList
     */
    getList: {
      name: "GetList",
      I: Empty,
      O: MyCouponsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.user.MyCouponController.Use
     */
    use: {
      name: "Use",
      I: CouponIDRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
} as const;

