// @generated by protoc-gen-connect-query v1.1.2 with parameter "target=ts,import_extension=.ts"
// @generated from file v1/user/Post.proto (package server.user, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Empty, MethodKind } from "@bufbuild/protobuf";
import { PostRequest, PostResponse, PostsResponse } from "./Post_pb.ts";

/**
 * お知らせ一覧を取得
 *
 * @generated from rpc server.user.PostController.GetPosts
 */
export const getPosts = {
  localName: "getPosts",
  name: "GetPosts",
  kind: MethodKind.Unary,
  I: Empty,
  O: PostsResponse,
  service: {
    typeName: "server.user.PostController"
  }
} as const;

/**
 * お知らせの詳細を取得
 *
 * @generated from rpc server.user.PostController.GetPostByID
 */
export const getPostByID = {
  localName: "getPostByID",
  name: "GetPostByID",
  kind: MethodKind.Unary,
  I: PostRequest,
  O: PostResponse,
  service: {
    typeName: "server.user.PostController"
  }
} as const;
