// @generated by protoc-gen-connect-es v1.1.3 with parameter "target=ts,import_extension=.ts"
// @generated from file v1/user/Store.proto (package server.user, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { SoreIDRequest } from "./Store_pb.ts";
import { StayableStore, StayableStores, Store, Stores } from "../shared/Store_pb.ts";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service server.user.StoreController
 */
export const StoreController = {
  typeName: "server.user.StoreController",
  methods: {
    /**
     * @generated from rpc server.user.StoreController.GetByID
     */
    getByID: {
      name: "GetByID",
      I: SoreIDRequest,
      O: Store,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.user.StoreController.GetAll
     */
    getAll: {
      name: "GetAll",
      I: Empty,
      O: Stores,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.user.StoreController.GetStayables
     */
    getStayables: {
      name: "GetStayables",
      I: Empty,
      O: StayableStores,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc server.user.StoreController.GetStayableByID
     */
    getStayableByID: {
      name: "GetStayableByID",
      I: SoreIDRequest,
      O: StayableStore,
      kind: MethodKind.Unary,
    },
  }
} as const;

