// @generated by protoc-gen-connect-es v1.1.3 with parameter "target=ts"
// @generated from file v1/user/UserReport.proto (package server.user, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { UserReportRequest } from "./UserReport_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service server.user.UserReportController
 */
export const UserReportController = {
  typeName: "server.user.UserReportController",
  methods: {
    /**
     * @generated from rpc server.user.UserReportController.Send
     */
    send: {
      name: "Send",
      I: UserReportRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
} as const;

