// @generated by protoc-gen-connect-query v1.1.2 with parameter "target=ts,import_extension=.ts"
// @generated from file v1/user/UserReport.proto (package server.user, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Empty, MethodKind } from "@bufbuild/protobuf";
import { UserReportRequest } from "./UserReport_pb.ts";

/**
 * @generated from rpc server.user.UserReportController.Send
 */
export const send = {
  localName: "send",
  name: "Send",
  kind: MethodKind.Unary,
  I: UserReportRequest,
  O: Empty,
  service: {
    typeName: "server.user.UserReportController"
  }
} as const;
